/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package boletin3;

public class App {
    public static void main(String[] args) {
        JsonManager jsonManager = new JsonManager();
        jsonManager.readLocationWheatherData("vigo");
    }
}
